# Run the following command to create this environment:
#   $ conda env create -f environment.yml
name: pytest-tutorial
dependencies:
  - python=3.7
  # Not necessary, but always useful
  - ipython
  - pytest
  - pip:
    - setuptools >=38.3.0
